### 
POST http://localhost:3012/reports
content-type: application/json

{
"make":"toyota",
"model":"Camry",
"year": 1980,
"mileage":100000,
"lng":0,
"lat":0,
"price":25000
}

### Approve an existing report 
PATCH http://localhost:3012/reports/1
content-type: application/json

{
    "approved": true
}

